---
# Copyleft (c) 2022 Contributors to Smart Data Models initiative
# 


components:
  schemas: 
    PublicOrganization: 
      $ref: "https://smart-data-models.github.io/dataModel.CPSV-AP/PublicOrganization/model.yaml#/PublicOrganization"
info:
  description:  |
    The CPSV-AP reuses the Core Public Organization Vocabulary (https://joinup.ec.europa.eu/asset/cpov/asset_release/all) that defines the concept of a Public Organization and associated properties and relationships. It is largely based on the W3C Organization Ontology (http://www.w3.org/TR/vocab-org).
  title: PublicOrganization
  version: "0.0.1"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - PublicOrganization
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.CPSV-AP/PublicOrganization/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.CPSV-AP/PublicOrganization/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
